### ISSUE TITLE
Remove not intervocalic t's from t_words

### ISSUE THREAD

**Issue by Gabrielsonnn** [Gabrielsonnn/Intervocalic-t-Search#6]
Search the file for any words which contain the following character sets:
VtV
VttV
Vtle
Vttle
ightV
Vt’
ight'
Where V = a, e, i, o, u, y

**Comment by allyugalde** [comment]
### VtV:
p**ity**, wr**iti**ng, e**ati**ng, pr**ete**nd, n**ote**d, n**ota**ble, l**ate**r, m**eta**l, gre**ate**st, hab**ita**t
**habitat**: hab-[ɪ**t**æ]-t

### VttV:
b**itte**n, m**itte**n, wr**itte**n, **atta**ck, k**itty**
**kitty**: k-[ɪ**t**i]

### Vtle & Vttle:
l**ittle**, br**ittle**, sh**uttle**
**little**: l-[ɪ**t**ə]-l

### ightV:
br**ighte**n, l**ighte**n, t**ighte**r, f**ighte**r, e**ightee**n
**tighter**: t[aɪ**t**ə]-r

### Vt':
**it**'ll, **it**'d
**it'll**: [ɪ**t**ə]-'ll

### ight':
might've
**might've**: m[aɪ**t**ə]-'ve

Note: Words like 'note', 'Pete', 'quote', 'mite', 'kite' are not intervocalic. Don't try to avoid these, keep these in the output and I'll manually take them out. In case there are words which end in an 'e' but aren't silent, I don't want to avoid missing those.

**Comment by Gabrielsonnn** [comment]
The way I'm planning on handling this is:

1. Read in all the words that have t in them

2. Change the the vowels a,e,i,o,u,y to V's. i.e. little -> lVttlV, yesterday -> VVstVrdVy, pity -> pVtV

3. Then test all the words against if statements that are checking to see if they contain VtV, VttV, and so on.

Does this seem like a valid way of implementing this functionality? Secondly, I noticed that for instance Vtle & Vttle, the e's in those aren't being changed to V's. Does this matter that they are e's? And why aren't they V's?

**Comment by allyugalde** [comment]
> Does this seem like a valid way of implementing this functionality?

Yes! I think this is a good way to do it, as long as the output is "little" and not "lVttlV"

> Secondly, I noticed that for instance Vtle & Vttle, the e's in those aren't being changed to V's. Does this matter that they are e's? And why aren't they V's?

If it's easier to use VtlV or VttlV then you can use those, because I can see now that something like "little" would become "lVttlV" and not be identified by the program as the "e" is a V. The reason the "e" is specified is because something like VtlV would output words like "quietly" [qui-**et-l**y] which aren't intervocalic. Worse case scenario, I have to remove the non-intervocalic words. It's not a big deal if it's something that takes a lot of time.
